alias rezshrc="source ~/.zshrc"
alias .="cd .."
alias ..="cd ../.."
alias ...="cd ../../.."
alias ....="cd ../../../.."
alias .....="cd ../../../../.."
alias ls="ls --color=auto -F"
alias ll="ls --color=auto -lF"
alias la="ls --color=auto -aF"
alias lla="ls --color=auto -alF"
